#!/usr/bin/env python3
import sys

inst = 0

def bf_to_verilog(bf_code):
    global inst
    print("// autogenerated brainfuck program")
    # print("always @* begin")
    print("    case (prog_addr)")
    for i, c in enumerate(bf_code):
        if c in '><+-.,[]':
            code = {
                '>': 0x3E,
                '<': 0x3C,
                '+': 0x2B,
                '-': 0x2D,
                '.': 0x2E,
                ',': 0x2C,
                '[': 0x5B,
                ']': 0x5D,
            }[c]
            print(f"        {inst}: prog_wr <= 8'h{code:02X};  // {c}")
            inst+=1
    print("        default: prog_wr <= 8'h00;")
    print("    endcase")
    print(" // number of instructions:", inst)
    # print("end")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: gen_bf.py file.bf > prog_rom.v")
        sys.exit(1)
    with open(sys.argv[1]) as f:
        bf_to_verilog(f.read())
        # print to stderr the number of instructions
        print(f"Wrote {inst} instructions", file=sys.stderr)